### ISSUE TITLE
1.3.0 is not compatable with PHP 7

### ISSUE THREAD

**Issue by equinoxmatt** [wesselperik/nova-status-field#2]
The package is marked as compatible with PHP 7, but in a recent commit, PHP 8 code was introduced:

https://github.com/wesselperik/nova-status-field/commit/dfdc03fea15ad123591dbe10d6502ffb5c72ac89

**Comment by wesselperik** [comment]
Hi @equinoxmatt, thanks for reporting! You are right indeed, I've removed the union types from the arguments in 1.3.1.
