### ISSUE TITLE
More Icons

### ISSUE THREAD

**Issue by jjjrmy** [wesselperik/nova-status-field#3]
Is there a way to add more icons or any icon dynamically from HeroIcons?
I'd like to use `exclamation`, `badge-check`, `shield-check`, `shield-exclamation`, `pause`, among other ones...

**Comment by wesselperik** [comment]
Hi @jjjrmy, this is not possible at the moment, but I like the idea very much! Might look into this when I have some spare time. And of course, if you want to help, feel free to do so! 😄

**Comment by jjjrmy** [comment]
I'll take a look when i get a chance, all the icon components are now baked into Nova

**Comment by jjjrmy** [comment]
#6
