### ISSUE TITLE
[v2.0.0] Crazy Side-Effect on Nova 4 Native Actionable Status Icons (disapears)

### ISSUE THREAD

**Issue by ibrainventures** [wesselperik/nova-status-field#5]
Thanks for your Package. 

After composering inside our Nova 4 System with activated actionable Model Display, 
the Status Icons are complete away.

![grafik](https://user-images.githubusercontent.com/8803626/169916489-035f0ea9-9466-40c0-909f-e3ccb90b576a.png)

**Without the package:**

![grafik](https://user-images.githubusercontent.com/8803626/169916651-83cd9bef-5fbb-4b20-8308-73f63245c1a5.png)

A fast inspection on the Native Icons shows, that your Component has "overtaken" (including all popper css-s) those Buttons.

**Comment by wesselperik** [comment]
Hi @ibrainventures, this is now fixed in v2.1.1!

<img width="1060" alt="image" src="https://user-images.githubusercontent.com/10948466/182910743-4ad71e78-d862-40fc-960f-83ca5416edea.png">
