### ISSUE TITLE
Status field with longer info text looks disorted and breaks single chars

### ISSUE THREAD

**Issue by chriswd** [wesselperik/nova-status-field#7]
Hey, thanks for developing this great component!

It currently has some issues if I insert a longer `info()`-text with the latest version of Laravel Nova 4:
- The icon becomes very small in responsive viewport sizes.
- Text breaks into single chars, which looks odd.
- The whole field looks quite compressed and the elements overlay each other.

Example:
<img width="1432" alt="Bildschirmfoto 2022-09-13 um 21 38 15" src="https://user-images.githubusercontent.com/4825463/189999229-e3f5218c-7376-4fdd-b84f-2b7104709232.png">

Could you please fix this?

**Comment by wesselperik** [comment]
Hi @chriswd, good catch! Thanks for reporting 😄 
I'm going to look into this, will let you know when this is fixed!

**Comment by wesselperik** [comment]
@chriswd fixed this in release v2.1.2!

<img width="385" alt="image" src="https://user-images.githubusercontent.com/10948466/190241575-56c54a70-551b-43a9-ae6e-ecebc62fde9e.png">

**Comment by chriswd** [comment]
@wesselperik This looks great, thank you!
